# Generated by Django 4.1.3 on 2022-11-05 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('form', models.CharField(max_length=30, null=True)),
                ('study_start', models.CharField(max_length=30, null=True)),
                ('study_form', models.CharField(max_length=30, null=True)),
                ('other_informations', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('value', models.FloatField()),
                ('type', models.CharField(choices=[('comment', 'Comment'), ('percentage', 'Percentage'), ('star', 'Star')], default='star', max_length=10)),
                ('comment', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=100)),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraperApp.portal')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('information', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scraperApp.information')),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraperApp.portal')),
                ('rating', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scraperApp.rating')),
            ],
        ),
    ]
