# Generated by Django 4.1.4 on 2022-12-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraperApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='other_information',
            field=models.JSONField(null=True),
        ),
    ]
