# Generated by Django 4.1.3 on 2022-11-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraperApp', '0002_alter_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='degree',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='languages',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
