# Generated by Django 4.1.4 on 2022-12-11 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraperApp', '0002_alter_course_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
