# Generated by Django 4.1.3 on 2022-11-18 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraperApp', '0003_information_degree_information_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='form',
        ),
    ]
