# Generated by Django 4.1.4 on 2023-01-05 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraperApp', '0003_alter_percentage_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image_url',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
