# Generated by Django 4.1.4 on 2022-12-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraperApp', '0004_alter_course_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='link',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='website_link',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
