# Generated by Django 4.1.5 on 2023-01-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraperApp', '0004_course_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='image_url',
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(max_length=500, null=True, upload_to='./static/'),
        ),
    ]
