# Generated by Django 4.1.3 on 2022-11-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraperApp', '0004_remove_information_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='study_periode',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
