# Generated by Django 4.1.4 on 2022-12-29 14:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraperApp', '0005_alter_bookmark_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='city',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='information',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, size=None),
        ),
    ]
