# Generated by Django 4.1.3 on 2022-11-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraperApp', '0007_alter_information_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='information',
            name='degree',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='languages',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='study_form',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='study_periode',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='study_start',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
