# Generated by Django 4.1.4 on 2022-12-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraperApp', '0008_alter_information_city_alter_information_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='city',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='information',
            name='languages',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
