# Generated by Django 4.1.5 on 2023-01-08 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraperApp', '0008_course_validated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='invalidated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invalidation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='validated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation', to=settings.AUTH_USER_MODEL),
        ),
    ]
