# Generated by Django 4.1.3 on 2022-11-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraperApp', '0010_remove_course_description_information_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='models',
            field=models.JSONField(null=True),
        ),
    ]
