# Generated by Django 4.1.5 on 2023-01-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraperApp', '0011_alter_logo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='image',
            field=models.ImageField(max_length=500, null=True, upload_to='./static/'),
        ),
    ]
