# Generated by Django 4.1.3 on 2022-11-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraperApp', '0011_information_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='other_informations',
        ),
        migrations.AddField(
            model_name='information',
            name='contents',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='costs',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='credit_points',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='requirements',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='website_link',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
