# Generated by Django 4.1.3 on 2022-11-28 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraperApp', '0012_remove_information_other_informations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.CharField(max_length=10, null=True)),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('star_rating', models.IntegerField()),
                ('additional_evaluation', models.JSONField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Percentage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.CharField(max_length=10, null=True)),
                ('title', models.CharField(max_length=30)),
                ('value', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.CharField(max_length=10, null=True)),
                ('title', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('value', models.CharField(max_length=30)),
                ('report_count', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='course',
            name='rating',
        ),
        migrations.AlterField(
            model_name='course',
            name='information',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scraperApp.information'),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.AddField(
            model_name='star',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraperApp.course'),
        ),
        migrations.AddField(
            model_name='percentage',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraperApp.course'),
        ),
        migrations.AddField(
            model_name='comment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraperApp.course'),
        ),
    ]
