# Generated by Django 4.1.3 on 2022-11-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraperApp', '0013_comment_percentage_star_remove_course_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='count',
        ),
        migrations.RemoveField(
            model_name='percentage',
            name='count',
        ),
        migrations.RemoveField(
            model_name='star',
            name='count',
        ),
        migrations.AddField(
            model_name='course',
            name='evaluation_count',
            field=models.IntegerField(null=True),
        ),
    ]
