# Generated by Django 4.1.3 on 2022-12-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraperApp', '0015_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='star_rating',
            field=models.CharField(max_length=5),
        ),
    ]
