# Generated by Django 4.1.3 on 2022-11-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraperApp', '0006_course_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='university',
            field=models.CharField(max_length=100),
        ),
    ]
