# Generated by Django 4.1.3 on 2022-11-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraperApp', '0009_course_description_course_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.AddField(
            model_name='information',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
