FROM node:18.12.0-alpine as build

WORKDIR /app/client
RUN yarn set version berry
COPY ./client/package.json ./
COPY ./client/yarn.lock ./
RUN yarn
RUN yarn rebuild esbuild
COPY ./client/ ./
ARG VITE_REACT_APP_API_URL

ENV VITE_REACT_APP_API_URL $VITE_REACT_APP_API_URL

RUN yarn build

FROM nginx:stable-alpine
COPY ./docker/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/client/build /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]