FROM python:3.11-buster


ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR /srv/app
ADD requirements.txt /srv/app/

RUN pip install --upgrade pip
RUN pip install gunicorn
RUN pip install -r requirements.txt
RUN mkdir scraperApp/static

COPY ./ ./
RUN chmod +x ./wsgi-entrypoint.sh

