FROM python:3.11-buster
RUN apt update
RUN apt-get install cron -y
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR /srv/app
ADD requirements.txt ./

RUN pip install --upgrade pip
RUN pip install gunicorn
RUN pip install -r requirements.txt

COPY ./ ./
RUN chmod +x ./wsgi-entrypoint.sh
COPY ./cron/crontab /etc/cron.d/crontab
RUN crontab /etc/cron.d/crontab
